net.Receive("RdmtApparitionBegin", function()
    local client = LocalPlayer()
    hook.Add("Think", "RdmtApparitionThink", function()
        Randomat:HandleEntitySmoke(ents.GetAll(), client, function(v)
            v:SetNoDraw(true)
            return v:GetNWBool("RdmtApparition", false)
        end)
    end)
end)

net.Receive("RdmtApparitionEnd", function()
    hook.Remove("Think", "RdmtApparitionThink")
end)