net.Receive("RdmtGaseousBegin", function()
    local client = LocalPlayer()
    hook.Add("Think", "RdmtGaseousThink", function()
        Randomat:HandlePlayerSmoke(client, function(v)
            return v:Alive() and not v:IsSpec()
        end)
    end)
end)

net.Receive("RdmtGaseousEnd", function()
    hook.Remove("Think", "RdmtGaseousThink")
end)